Repository gamedaoco/gamedao-haiku, pull requests merged in 2022-07, with the labels that each got.

#216 feat(balance): add balance logic to service
  pkg/service/package.json
  pkg/service/prisma/migrations/20220630101353_add_session/migration.sql
  pkg/service/prisma/migrations/20220701100239_add_balance/migration.sql
  pkg/service/prisma/schema.prisma
  pkg/service/src/@types/schema.d.ts
  pkg/service/src/main.ts
  pkg/service/src/modules/balanceManager.ts
  pkg/service/src/modules/sessionManager.ts
  pkg/service/src/resolvers/mutation/updateSessionResolver.ts
  pkg/service/src/resolvers/resolvers.ts
  pkg/service/src/schema.graphql
  pkg/service/src/utils/accountUtils.ts
Labels: graphql

#224 feat(squid-add-withdrawal-granted-handler): added withdrawal granted handler
  pkg/app/src/theme/typography.ts
  pkg/squid/src/handlers/signal/events/withdrawalGrantedHandler.ts
  pkg/squid/src/handlers/signal/index.ts
  pkg/squid/src/types/events.ts
  pkg/squid/typegen.json
Labels: haiku, graphql

#227 feat(create-campaign-step-one): adds create campaign step one page
  pkg/app/src/@types/campaign.d.ts
  pkg/app/src/components/Forms/Campaign/form.tsx
  pkg/app/src/components/Forms/Campaign/modules/name.tsx
  pkg/app/src/components/TabPanels/Campaign/create.tsx
  pkg/app/src/components/TabPanels/Campaign/overview.tsx
  pkg/app/src/hooks/useTmpCampaignState.ts
  pkg/app/src/pages/organisations/[...param].tsx
Labels: haiku, Frontend

#228 feat(balances): add balance subscription
  .gitignore
  pkg/app/src/components/BalanceCard/balanceCard.tsx
  pkg/app/src/components/TransactionDialog/transactionDialog.tsx
  pkg/app/src/constants/index.ts
  pkg/app/src/hooks/tx/useCreateProposalTransaction.ts
  pkg/app/src/hooks/useBalanceByAddress.ts
  pkg/app/src/hooks/useBalanceByAddressAndBalanceId.ts
  pkg/app/src/hooks/useSystemProperties.ts
  pkg/app/src/provider/extension/extensionProvider.tsx
  pkg/app/src/queries/balance.graphql
  pkg/app/src/queries/index.ts
  pkg/app/src/queries/session.graphql
  pkg/app/src/utils/balance.ts
Labels: enhancement, haiku

#266 feat(campaign-card): update card and list
  pkg/app/package.json
  pkg/app/src/@types/campaignStatus.ts
  pkg/app/src/components/Account/modules/myCampaignsTab.tsx
  pkg/app/src/components/CampaignCard/campaignCard.tsx
  pkg/app/src/components/CampaignCard/modules/content.tsx
  pkg/app/src/components/CampaignCard/modules/header.tsx
  pkg/app/src/components/CampaignCard/modules/shape-avatar.svg
  pkg/app/src/components/CampaignCard/modules/statusChip.tsx
  pkg/app/src/components/CampaignsList/campaignsList.tsx
  pkg/app/src/components/CampaignsSection/CampaignsList/campaignCard.tsx
  pkg/app/src/components/CampaignsSection/CampaignsList/campaignsList.tsx
  pkg/app/src/components/CampaignsSection/CampaignsList/loadingCampaignCard.tsx
  pkg/app/src/components/Image/image.tsx
  pkg/app/src/components/Image/modules/img_placeholder.svg
  pkg/app/src/components/SvgIconStyle/svgIconStyle.tsx
  pkg/app/src/components/TabPanels/Campaign/overview.tsx
  pkg/app/src/constants/campaign.ts
  pkg/app/src/queries/campaigns.graphql
  pkg/app/src/theme/overrides/Chip.tsx
  pkg/app/src/theme/palette.ts
  pkg/app/src/utils/campaignUtils.ts
  pkg/app/src/utils/token.ts
  pkg/translations/src/app/en-US.json
  yarn.lock
Labels: haiku

#261 feat(create-campaign-step-two): campaign creation step two
  pkg/app/package.json
  pkg/app/src/@types/campaign.d.ts
  pkg/app/src/components/Dropzone/dropzone.tsx
  pkg/app/src/components/Forms/Campaign/form.tsx
  pkg/app/src/components/Forms/Campaign/modules/content.tsx
  pkg/app/src/constants/index.ts
  pkg/app/src/hooks/useTmpCampaignState.ts
  yarn.lock
Labels: haiku, Frontend

#257 feat(page): campaigns list
  pkg/app/src/@types/campaign.d.ts
  pkg/app/src/components/CampaignsSection/CampaignFilters/CampaignFiltersTab.tsx
  pkg/app/src/components/FiltersSections/filtersSection.tsx
  pkg/app/src/components/FiltersSections/sortOptionsTab.tsx
  pkg/app/src/components/OrganisationCard/modules/listTab.tsx
  pkg/app/src/pages/campaigns/index.tsx
  pkg/app/src/pages/organisations/index.tsx
  pkg/app/src/queries/campaigns.graphql
  pkg/app/src/queries/displayValues.graphql
  pkg/translations/src/app/en-US.json
Labels: haiku, Frontend

#279 feat: organization no campaigns
  pkg/app/src/components/TabPanels/Campaign/overview.tsx
  pkg/translations/src/app/en-US.json
Labels: haiku, Frontend

#284 feat(service-campaign-categories): adds campaign funding categories
  pkg/service/src/@types/schema.d.ts
  pkg/service/src/resolvers/query/displayValues/data.json
  pkg/service/src/schema.graphql
Labels: graphql

#282 fix: update query and update balance id
  pkg/app/src/components/BalanceCard/balanceCard.tsx
  pkg/app/src/queries/campaigns.graphql
Labels: bug

#296 chore: bump packages
  package.json
  pkg/app/package.json
  pkg/app/src/utils/token.ts
  pkg/service/package.json
  pkg/squid/package.json
  yarn.lock
Labels: dependencies

#281 feat(create-campaign-step-three): added step 3
  pkg/app/src/@types/campaign.d.ts
  pkg/app/src/components/Forms/Campaign/form.tsx
  pkg/app/src/components/Forms/Campaign/modules/content.tsx
  pkg/app/src/components/Forms/Campaign/modules/settings.tsx
  pkg/app/src/components/TabPanels/Campaign/create.tsx
  pkg/app/src/components/TransactionDialog/transactionDialog.tsx
  pkg/app/src/constants/index.ts
  pkg/app/src/hooks/tx/useCreateCampaignTransaction.ts
  pkg/app/src/hooks/useTmpCampaign.ts
  pkg/app/src/hooks/useTmpCampaignState.ts
  pkg/app/src/queries/displayValues.graphql
  pkg/translations/src/app/en-US.json
Labels: haiku, Frontend

#304 fix: time from block calculation
  pkg/app/src/utils/campaignUtils.ts
Labels: bug

#303 feat(contribute-to-campaign): update modal and add transaction
  pkg/app/src/components/CampaignsSection/campaignDetailsContent.tsx
  pkg/app/src/components/TransactionDialog/modules/contributeSection.tsx
  pkg/app/src/components/TransactionDialog/transactionDialog.tsx
  pkg/app/src/hooks/tx/useContributeTransaction.ts
  pkg/app/src/pages/campaigns/[id].tsx
  pkg/app/src/queries/campaigns.graphql
  pkg/translations/src/app/en-US.json
Labels: enhancement

#305 fix: proposal vote
  pkg/app/src/components/TabPanels/Proposal/detail.tsx
  pkg/app/src/components/TabPanels/Proposal/overview.tsx
  pkg/app/src/hooks/tx/useSimpleVoteTransaction.ts
Labels: bug

#306 fix: update links
  pkg/app/src/components/TabPanels/Organization/tmpOverview.tsx
  pkg/app/src/components/TransactionDialog/transactionDialog.tsx
  pkg/app/src/utils/campaignUtils.ts
Labels: bug

#314 fix(graphql): organization member sort
  pkg/service/package.json
  pkg/service/src/resolvers/query/displayValues/data.json
Labels: bug, haiku, Frontend

#321 feat(blockTime): add blocktime to service
  pkg/service/src/@types/schema.d.ts
  pkg/service/src/resolvers/query/apiProviders/apiProviderResolver.ts
  pkg/service/src/resolvers/query/config/config.json
  pkg/service/src/schema.graphql
Labels: graphql

#322 fix: withdrawal token decimals
  pkg/app/src/hooks/tx/useCreateProposalTransaction.ts
  pkg/app/src/queries/config.graphql
Labels: bug
