Repository gamedaoco/gamedao-haiku, pull requests merged in 2022-06, with the labels that each got.

#175 fix: local storage value sync
  pkg/app/src/hooks/useLocalStorage.ts
Labels: bug, haiku, Frontend

#174 feat(view-proposal): adds proposal overview page
  .gitignore
  pkg/app/package.json
  pkg/app/src/components/ProposalOverview/proposalOverview.tsx
  pkg/app/src/components/TabPanels/Organization/createProposal.tsx
  pkg/app/src/components/TabPanels/Organization/proposals.tsx
  pkg/app/src/hooks/useLocalStorage.ts
  pkg/app/src/lib/logger.ts
  pkg/app/src/pages/organisations/[...param].tsx
  pkg/app/src/theme/overrides/Chip.tsx
Labels: haiku, Frontend

#185 feat(proposal-detail-page): adds proposal detail page
  pkg/app/src/components/Forms/baseForm.tsx
  pkg/app/src/components/Forms/modules/radioItem.tsx
  pkg/app/src/components/ProposalStatusChip/ProposalStatusChip.tsx
  pkg/app/src/components/TabPanels/Proposal/detail.tsx
  pkg/app/src/components/TabPanels/Proposal/overview.tsx
  pkg/app/src/pages/organisations/[...param].tsx
  pkg/app/src/theme/overrides/Chip.tsx
Labels: haiku, Frontend

#196 feat(add-header-image): adds header image
  pkg/app/src/pages/organisations/[...param].tsx
  pkg/app/src/queries/index.ts
  pkg/app/src/queries/organizations.graphql
Labels: haiku, Frontend

#197 feat(withdraw-proposal): add withdraw form
  pkg/app/src/components/Forms/Proposal/form.tsx
  pkg/app/src/components/Forms/Proposal/modules/description.tsx
  pkg/app/src/hooks/tx/useCreateProposalTransaction.ts
  pkg/app/src/pages/api/translation.ts
  pkg/app/src/pages/organisations/[...param].tsx
  pkg/app/src/provider/language/modules/i18n.ts
  pkg/app/src/queries/campaigns.graphql
  pkg/app/src/queries/index.ts
  pkg/translations/package.json
  pkg/translations/src/app/index.ts
  pkg/translations/src/index.ts
  pkg/translations/tsconfig.json
  yarn.lock
Labels: haiku, Frontend

#201 fix: dialog behaviour
  pkg/app/src/components/BaseDialog/baseDialog.tsx
Labels: bug

#202 feat(org-features): update files
  pkg/service/src/@types/schema.d.ts
  pkg/service/src/resolvers/query/displayValues/data.json
  pkg/service/src/resolvers/query/features/features.json
  pkg/service/src/schema.graphql
  pkg/translations/src/app/en-US.json
Labels: graphql

#204 feat(squid-proposals): adds proposal to squid (graphql)
  pkg/squid/.env.example
  pkg/squid/db/migrations/1653754590901-init.js
  pkg/squid/db/migrations/1656424755677-addProposals.js
  pkg/squid/schema.graphql
  pkg/squid/src/@types/ipfs/proposalMetadata.ts
  pkg/squid/src/@types/pallets/flow/campaignCreationData.d.ts
  pkg/squid/src/@types/pallets/governance/proposalCreationData.d.ts
  pkg/squid/src/@types/pallets/signal/proposalCreationData.ts
  pkg/squid/src/@types/pallets/signal/proposalSimpleVoteData.ts
  pkg/squid/src/database/campaign.ts
  pkg/squid/src/database/proposal.ts
  pkg/squid/src/database/proposalMetadata.ts
  pkg/squid/src/database/proposalVoter.ts
  pkg/squid/src/handlers/flow/events/campaignCreatedHandler.ts
  pkg/squid/src/handlers/index.ts
  pkg/squid/src/handlers/signal/events/proposalApprovedHandler.ts
  pkg/squid/src/handlers/signal/events/proposalCreatedHandler.ts
  pkg/squid/src/handlers/signal/events/proposalExpiredHandler.ts
  pkg/squid/src/handlers/signal/events/proposalHandler.ts
  pkg/squid/src/handlers/signal/events/proposalRejectedHandler.ts
  pkg/squid/src/handlers/signal/events/proposalVotedHandler.ts
  pkg/squid/src/handlers/signal/events/sharedCreateProposalHandler.ts
  pkg/squid/src/handlers/signal/index.ts
  pkg/squid/src/ipfs/ipfs.ts
  pkg/squid/src/model/generated/_proposalTypeData.ts
  pkg/squid/src/model/generated/_proposalTypeWithdrawalData.ts
  pkg/squid/src/model/generated/campaign.model.ts
  pkg/squid/src/model/generated/identity.model.ts
  pkg/squid/src/model/generated/index.ts
  pkg/squid/src/model/generated/organization.model.ts
  pkg/squid/src/model/generated/proposal.model.ts
  pkg/squid/src/model/generated/proposalMetadata.model.ts
  pkg/squid/src/model/generated/proposalVoter.model.ts
  pkg/squid/src/transformer/campaignCreateDataTransformer.ts
  pkg/squid/src/transformer/proposalCreateDataTransformer.ts
  pkg/squid/src/types/calls.ts
  pkg/squid/src/types/events.ts
  pkg/squid/typegen.json
Labels: haiku, graphql

#205 feat(nft-chain-data): rmrk nfts and chain data to graphql
  pkg/service/.env.example
  pkg/service/package.json
  pkg/service/src/@types/schema.d.ts
  pkg/service/src/chainTypes/zero-types.json
  pkg/service/src/main.ts
  pkg/service/src/modules/chainClient.ts
  pkg/service/src/modules/pubSub.ts
  pkg/service/src/resolvers/query/apiProviders/apiProviderResolver.ts
  pkg/service/src/resolvers/query/rmrk/nftsResolver.ts
  pkg/service/src/resolvers/resolvers.ts
  pkg/service/src/resolvers/subscriptions/blockNumbersubscription.ts
  pkg/service/src/schema.graphql
  pkg/service/src/utils/accountUtils.ts
  yarn.lock
Labels: graphql, tech

#210 feat(chain-settings): load config and types from graphql
  pkg/app/src/@types/app.ts
  pkg/app/src/@types/network.d.ts
  pkg/app/src/components/AccountSelector/modules/flyout.tsx
  pkg/app/src/data/zero-types.json
  pkg/app/src/hooks/tx/useCreateOrgTransaction.ts
  pkg/app/src/hooks/tx/useCreateProposalTransaction.ts
  pkg/app/src/hooks/useBalanceByAddress.ts
  pkg/app/src/hooks/useBlockNumber.ts
  pkg/app/src/provider/app/appProvider.tsx
  pkg/app/src/provider/app/modules/context.ts
  pkg/app/src/provider/network/modules/network.ts
  pkg/app/src/provider/network/networkProvider.tsx
  pkg/app/src/provider/provider.tsx
  pkg/app/src/queries/blockNumber.graphql
  pkg/app/src/queries/config.graphql
  pkg/app/src/queries/index.ts
Labels: enhancement, haiku, graphql

#214 fix(proposal-data): added general proposal data
  pkg/squid/schema.graphql
  pkg/squid/src/database/proposal.ts
  pkg/squid/src/model/generated/_proposalTypeData.ts
  pkg/squid/src/model/generated/_proposalTypeGeneralData.ts
  pkg/squid/src/model/generated/_proposalTypeWithdrawalData.ts
  pkg/squid/src/model/generated/index.ts
Labels: haiku, graphql
