Repository gamedaoco/gamedao-haiku, pull requests merged in 2022-03, with the labels that each got.

#48 feat(subsquid-graphql): add subsquid subschema to graphql
  pkg/app/src/pages/api/graphql.ts
  pkg/graphql/scripts/mergeSchemas.js
  pkg/graphql/src/executors/index.ts
  pkg/graphql/src/executors/subsquid.ts
  pkg/graphql/src/query/index.ts
  pkg/graphql/src/resolver/resolvers-types.ts
  pkg/graphql/src/schema/schema.graphql
  pkg/graphql/src/types/index.ts
Labels: haiku, Frontend

#49 chore: update readme
  README.md
Labels: haiku

#50 feat(add-fe-subsquid-example): added example how to retrieve chain data from graphql
  pkg/app/src/pages/app/governance.tsx
  pkg/graphql/src/query/index.ts
  pkg/graphql/src/schema/queries/bodies.graphql
Labels: haiku, Frontend

#56 feat(update-subsquid-example): updated example and added identity data
  pkg/app/src/pages/app/governance.tsx
  pkg/graphql/scripts/mergeSchemas.js
  pkg/graphql/src/executors/subsquid.ts
  pkg/graphql/src/query/index.ts
  pkg/graphql/src/resolver/resolvers-types.ts
  pkg/graphql/src/schema/queries/bodies.graphql
  pkg/graphql/src/schema/schema.graphql
  pkg/graphql/src/types/index.ts
Labels: enhancement, haiku, Frontend

#58 feat(three Forms): Create Dao/Proposal/Campaign Form with custom mui components using react-hook-form and yup
  pkg/app/package.json
  pkg/app/src/components/Forms/FormCampaign.tsx
  pkg/app/src/components/Forms/FormDao.tsx
  pkg/app/src/components/Forms/FormVoting.tsx
  pkg/app/src/components/Forms/modules/autocomplete.tsx
  pkg/app/src/components/Forms/modules/checkbox.tsx
  pkg/app/src/components/Forms/modules/input.tsx
  pkg/app/src/components/Forms/modules/stepper.tsx
  pkg/app/src/pages/app/campaigns/index.tsx
  pkg/app/src/pages/app/governance.tsx
  pkg/app/src/pages/app/index.tsx
  pkg/app/src/utils/accountUtils.ts
  pkg/app/src/utils/data.ts
  yarn.lock
Labels: haiku, Frontend
