Repository gamedaoco/gamedao-haiku, pull requests merged in 2022-09, with the labels that each got.

#383 fix: update styles
  pkg/app/src/pages/organisations/[...param].tsx
Labels: bug, haiku

#381 fix: fix table style
  pkg/app/src/@types/campaign.d.ts
  pkg/app/src/components/Account/modules/OverviewSection/myBalances.tsx
  pkg/app/src/components/Forms/Campaign/form.tsx
  pkg/app/src/components/Forms/Campaign/modules/settings.tsx
  pkg/app/src/constants/index.ts
  pkg/app/src/hooks/useTmpCampaign.ts
  pkg/app/src/hooks/useTmpCampaignState.ts
  pkg/app/src/pages/account/index.js
  pkg/app/src/pages/account/index.tsx
  pkg/app/src/theme/overrides/Table.ts
Labels: bug, haiku

#389 fix(org-creation): disabled click events on overlay box
  pkg/app/src/pages/organisations/[...param].tsx
Labels: bug, haiku, Frontend

#403 fix: block duration
  pkg/service/docker-compose-test.yml
  pkg/service/src/resolvers/query/apiProviders/apiProviderResolver.ts
  yarn.lock
Labels: bug, tech

#398 fix(render-editor-content): render editor content
  pkg/app/package.json
  pkg/app/src/components/Editor/editorWrapper.tsx
  pkg/app/src/components/Editor/index.tsx
  pkg/app/src/pages/campaigns/[id].tsx
  yarn.lock
Labels: bug, haiku, Frontend

#408 chore: update development environment
  pkg/app/src/components/Account/modules/OverviewSection/myBalances.tsx
  pkg/dev-env/.env.example
  pkg/dev-env/docker-compose.yml
  pkg/dev-env/hasura_metadata.json
  pkg/dev-env/node/.gitignore
  pkg/dev-env/node/chainspec/rococo-local-plain.json
  pkg/dev-env/node/chainspec/rococo-local-raw.json
  pkg/dev-env/node/chainspec/subzero-parachain-plain.json
  pkg/dev-env/node/chainspec/subzero-parachain-raw.json
  pkg/dev-env/node/wasm/subzero-genesis
  pkg/dev-env/node/wasm/subzero-wasm
Labels: haiku, Frontend, testing

#421 feat(update-dev-env-prune-node): updated parachain-a to full node
  pkg/dev-env/docker-compose.yml
Labels: enhancement
