Repository gamedaoco/gamedao-haiku, pull requests merged in 2022-08, with the labels that each got.

#315 fix: translations
  pkg/app/src/components/Account/modules/IdentitySection/form.tsx
  pkg/app/src/components/Account/modules/MyOrganisations/myOrganisations.tsx
  pkg/app/src/components/Account/modules/OverviewSection/myAchievements.tsx
  pkg/app/src/components/Account/modules/OverviewSection/myBalances.tsx
  pkg/app/src/components/Account/modules/identitySection.tsx
  pkg/app/src/components/Account/modules/myCollectablesTab.tsx
  pkg/app/src/components/Account/modules/myOrganisationsTab.tsx
  pkg/app/src/components/Account/modules/overviewTab.tsx
  pkg/app/src/components/Account/modules/tabsSection.tsx
  pkg/app/src/components/CampaignsSection/ContributedCampaignsSection/contributedCampaignsSection.tsx
  pkg/app/src/components/Forms/Organization/form.tsx
  pkg/app/src/components/NoWalletConnected/noWalletConnected.tsx
  pkg/app/src/components/OrganisationCard/modules/tileCard.tsx
  pkg/app/src/components/TabPanels/Organization/organizationMembers.tsx
  pkg/app/src/components/TabPanels/Organization/overview.tsx
  pkg/app/src/components/TabPanels/Organization/tmpOverview.tsx
  pkg/app/src/components/TabPanels/Proposal/detail.tsx
  pkg/app/src/components/TabPanels/Proposal/overview.tsx
  pkg/app/src/pages/account/[path].tsx
  pkg/app/src/pages/campaigns/index.tsx
  pkg/app/src/pages/organisations/[...param].tsx
  pkg/app/src/pages/organisations/create.tsx
  pkg/app/src/pages/organisations/index.tsx
  pkg/translations/src/app/en-US.json
Labels: bug, enhancement, haiku, Frontend

#328 fix: campaign details page
  pkg/app/src/components/CampaignsSection/campaignDetailsContent.tsx
  pkg/app/src/pages/campaigns/[id].tsx
Labels: bug, haiku, Frontend

#331 fix: organization translation
  pkg/translations/src/app/en-US.json
Labels: bug

#333 fix: use dev env only on development build
  pkg/app/.env.development
Labels: bug

#334 fix: campaing progress bar
  pkg/app/src/components/CampaignsSection/campaignDetailsContent.tsx
  pkg/app/src/utils/campaignUtils.ts
Labels: bug

#313 feat(update-squid-processor): update GraphQL
  pkg/dev-env/config/customSpec.json
  pkg/dev-env/config/typesBundle.json
  pkg/dev-env/docker-compose.yml
  pkg/dev-env/testConsole.js
  pkg/squid/db/migrations/1659438646716-updateOrgAssetTypes.js
  pkg/squid/schema.graphql
  pkg/squid/src/@types/pallets/control/orgCreationData.ts
  pkg/squid/src/@types/pallets/flow/campaignCreationData.d.ts
  pkg/squid/src/config.json
  pkg/squid/src/handlerMapping.ts
  pkg/squid/src/handlers/control/events/addMemberHandler.ts
  pkg/squid/src/handlers/control/events/orgCreatedHandler.ts
  pkg/squid/src/handlers/control/events/removeMemberHandler.ts
  pkg/squid/src/handlers/flow/events/campaignContributedHandler.ts
  pkg/squid/src/handlers/flow/events/campaignCreatedHandler.ts
  pkg/squid/src/handlers/flow/events/campaignFailedHandler.ts
  pkg/squid/src/handlers/flow/events/campaignFinalizedHandler.ts
  pkg/squid/src/handlers/flow/events/campaignUpdatedHandler.ts
  pkg/squid/src/handlers/signal/events/proposalApprovedHandler.ts
  pkg/squid/src/handlers/signal/events/proposalCreatedHandler.ts
  pkg/squid/src/handlers/signal/events/proposalExpiredHandler.ts
  pkg/squid/src/handlers/signal/events/proposalHandler.ts
  pkg/squid/src/handlers/signal/events/proposalRejectedHandler.ts
  pkg/squid/src/handlers/signal/events/proposalVotedHandler.ts
  pkg/squid/src/handlers/signal/events/withdrawalGrantedHandler.ts
  pkg/squid/src/ipfs/campaign.ts
  pkg/squid/src/ipfs/organization.ts
  pkg/squid/src/ipfs/proposal.ts
  pkg/squid/src/model/generated/organization.model.ts
  pkg/squid/src/transformer/campaignCreateDataTransformer.ts
  pkg/squid/src/transformer/organizationCreateDataTransformer.ts
  pkg/squid/src/transformer/proposalCreateDataTransformer.ts
  pkg/squid/src/types/calls.ts
  pkg/squid/src/types/events.ts
  pkg/squid/src/types/v51.ts
  pkg/squid/src/types/v58.ts
  pkg/squid/zeroTypesBundle.json
  pkg/squid/zeroVersions.json
Labels: haiku, Frontend, graphql

#341 fix: create organization callback
  pkg/app/src/pages/organisations/index.tsx
Labels: bug, haiku, Frontend

#336 chore: add readme for dev-env
  pkg/dev-env/README.md
Labels: haiku

#347 feat(campaign-draft): add logic for campaign draft
  pkg/app/.env.development
  pkg/app/src/@types/campaign.d.ts
  pkg/app/src/@types/campaignStatus.ts
  pkg/app/src/components/CampaignCard/campaignCard.tsx
  pkg/app/src/components/CampaignCard/modules/statusChip.tsx
  pkg/app/src/components/CampaignsList/campaignsList.tsx
  pkg/app/src/components/Forms/Campaign/form.tsx
  pkg/app/src/components/TabPanels/Campaign/create.tsx
  pkg/app/src/components/TabPanels/Campaign/overview.tsx
  pkg/app/src/hooks/useSaveCampaignDraft.ts
  pkg/app/src/hooks/useTmpCampaignState.ts
  pkg/app/src/theme/overrides/Chip.tsx
  pkg/app/src/theme/palette.ts
  pkg/translations/src/app/en-US.json
Labels: enhancement, haiku

#348 feat(update-squid): updated versions
  pkg/squid/src/config.json
  pkg/squid/zeroVersions.json
Labels: haiku, graphql

#349 feat(fix-service): removed types, fixed chain communication
  pkg/service/docker-compose-test.yml
  pkg/service/src/chainTypes/zero-types.json
  pkg/service/src/main.ts
  pkg/service/src/modules/balanceManager.ts
  pkg/service/src/modules/chainClient.ts
  pkg/service/src/resolvers/query/apiProviders/apiProviderResolver.ts
Labels: haiku, graphql

#350 fix(service): removed zero from tokens
  pkg/service/src/modules/balanceManager.ts
Labels: haiku, graphql

#351 fix: dao transaction
  pkg/app/src/hooks/tx/useCreateOrgTransaction.ts
  pkg/app/src/utils/token.ts
Labels: bug

#242 feat(mobile-wallet): add polkawallet
  pkg/app/src/components/WalletDialog/walletDialog.tsx
  pkg/app/src/provider/extension/extensionProvider.tsx
  pkg/app/src/provider/extension/modules/accounts.ts
  pkg/app/src/walletOverrides/polkawallet-wallet/index.ts
  pkg/app/src/walletOverrides/polkawallet-wallet/logo.png
  pkg/app/src/walletOverrides/wallets.ts
Labels: bug, haiku, tech

#343 feat(#332): organisation settings page
  pkg/app/src/components/TabPanels/Settings/modules/about.tsx
  pkg/app/src/components/TabPanels/Settings/modules/accessType.tsx
  pkg/app/src/components/TabPanels/Settings/modules/control.tsx
  pkg/app/src/components/TabPanels/Settings/modules/memberLimit.tsx
  pkg/app/src/components/TabPanels/Settings/modules/memberType.tsx
  pkg/app/src/components/TabPanels/Settings/settings.tsx
  pkg/app/src/hooks/tx/useCreateOrgTransaction.ts
  pkg/app/src/hooks/useDisplayValues.ts
  pkg/app/src/pages/organisations/[...param].tsx
  pkg/app/src/queries/displayValues.graphql
  pkg/translations/src/app/en-US.json
Labels: enhancement, haiku, graphql

#367 fix: fix connect logic
  pkg/app/src/components/AccountSelector/accountSelector.tsx
  pkg/app/src/provider/extension/extensionProvider.tsx
  pkg/translations/src/app/en-US.json
Labels: bug, haiku

#364 feat(network-switch): add network switch
  pkg/app/.env
  pkg/app/.env.development
  pkg/app/src/@types/graphql.d.ts
  pkg/app/src/components/AccountSelector/modules/flyout.tsx
  pkg/app/src/components/SelectNetworkDialog/modules/networkCard.tsx
  pkg/app/src/components/SelectNetworkDialog/selectNetworkDialog.tsx
  pkg/app/src/constants/endpoints.ts
  pkg/app/src/provider/graphQl/graphQlProvider.tsx
  pkg/app/src/provider/graphQl/modules/context.ts
  pkg/app/src/provider/graphQl/modules/graphQl.ts
  pkg/app/src/provider/provider.tsx
  pkg/translations/src/app/en-US.json
Labels: enhancement, haiku

#366 feat(delete-draft): add delete buttons and modal
  pkg/app/src/components/CampaignCard/campaignCard.tsx
  pkg/app/src/components/CampaignCard/modules/header.tsx
  pkg/app/src/components/Forms/Campaign/form.tsx
  pkg/app/src/components/Modals/confirmDeleteCampaignDraft.tsx
  pkg/app/src/components/TabPanels/Campaign/overview.tsx
  pkg/app/src/hooks/useSaveCampaignDraft.ts
  pkg/app/src/theme/overrides/Chip.tsx
  pkg/translations/src/app/en-US.json
Labels: enhancement, haiku

#378 feat(global-text-editor): fixed editor, added resizer and drag&drop m…
  pkg/app/package.json
  pkg/app/src/components/Editor/editorToolbar.tsx
  pkg/app/src/components/Editor/editorToolbarStyled.tsx
  pkg/app/src/components/Editor/editorWrapper.tsx
  pkg/app/src/components/Editor/index.tsx
  pkg/app/src/components/Forms/Campaign/modules/content.tsx
  pkg/app/src/lib/quillImageDropModule.ts
  pkg/app/src/lib/quillImageResizerModule/DefaultOptions.ts
  pkg/app/src/lib/quillImageResizerModule/ImageResize.ts
  pkg/app/src/lib/quillImageResizerModule/modules/BaseModule.ts
  pkg/app/src/lib/quillImageResizerModule/modules/DisplaySize.ts
  pkg/app/src/lib/quillImageResizerModule/modules/Resize.ts
  pkg/app/src/pages/index.tsx
  pkg/app/src/provider/theme/themeProvider.tsx
  pkg/app/src/utils/file.ts
  yarn.lock
Labels: haiku, Frontend
